---
- hosts: servidorhttp
  sudo: true
  tasks:

  - name: actualizar cache (apt-get update)
    apt: update_cache=yes cache_valid_time=3600
    sudo: yes

  - name: instalar paquetes requeridos
    sudo: yes
    apt: name={{ item }} state=present
    with_items:
    - apache2
    - php5
    - php5-mysql
    - libapache2-mod-php5
    - php5-mcrypt

  - name: Instalar extenciones de php
    apt: name={{ item }} state=present
    sudo: yes
    with_items:
    - php5-gd 
    - libssh2-php

  - name: Descargar wordpress de internet
    sudo: yes
    get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz validate_certs=no

  - name: Extraer wordpress
    unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no 
    sudo: yes

  - name: Configurar apache2 para que pueda mostrar el sitio web de Wordpress
    sudo: yes
    lineinfile: dest=/etc/apache2/sites-enabled/000-default.conf regexp="(.)+DocumentRoot /var/www/html" line="DocumentRoot /var/www/wordpress"
    notify:
    - restart apache

  - name: reiniciar apache
    service: name=apache2 state=restarted
    sudo: yes

  - name: Apuntar wordpress a nuestro servidorDB
    lineinfile: dest=/var/www/wordpress/wp-config-sample.php regexp="{{ item.regexp }}" line="{{ item.line }}"
    with_items: 
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', 'wordpress');"}        
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', 'wordpress');"}        
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', 'wordpress');"}
    - {'regexp': "define\\('DB_HOST', '(.)+'\\);", 'line': "define('DB_HOST', '192.168.100.30');"}
    sudo: yes